compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

pnpFallbackMode: all

pnpMode: loose

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.11.0.cjs
