# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2025 ActiDoo GmbH

"""userlocale

Revision ID: 10d894b60910
Revises: 957e40296322
Create Date: 2025-05-13 12:09:24.421413

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '10d894b60910'
down_revision = '38f22a088623'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_users', sa.Column('locale', sa.String(length=10), nullable=True, comment="IETF BCP 47 locale string, e.g. 'de-DE', 'en', 'fr-CH'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_users', 'locale')
    # ### end Alembic commands ###
