"""zlibjson

Revision ID: 38f22a088623
Revises: 957e40296322
Create Date: 2025-05-07 12:03:11.795824

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import actidoo_wfe.database
import json
import zlib
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision = '38f22a088623'
down_revision = '5ac6c99dbe4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflow_instance_tasks', 'data',
               existing_type=mysql.LONGTEXT(),
               type_=actidoo_wfe.database.ZlibJSONBlob(),
               existing_nullable=True)
    op.alter_column('workflow_instance_tasks', 'jsonschema',
               existing_type=mysql.LONGTEXT(),
               type_=actidoo_wfe.database.ZlibJSONBlob(),
               existing_nullable=True)
    op.alter_column('workflow_instance_tasks', 'uischema',
               existing_type=mysql.LONGTEXT(),
               type_=actidoo_wfe.database.ZlibJSONBlob(),
               existing_nullable=True)
    op.alter_column('workflow_instances', 'data',
               existing_type=mysql.LONGTEXT(),
               type_=actidoo_wfe.database.ZlibJSONBlob(),
               existing_nullable=False)
    op.alter_column('workflow_messages', 'data',
               existing_type=mysql.LONGTEXT(),
               type_=actidoo_wfe.database.ZlibJSONBlob(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
