"""storage abstraction

Revision ID: 5ac6c99dbe4b
Revises: 957e40296322
Create Date: 2025-04-02 09:19:41.415953

"""
import sqlalchemy as sa
import sqlalchemy_file.types
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ac6c99dbe4b'
down_revision = '957e40296322'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_attachments', sa.Column('file', sqlalchemy_file.types.FileField(), nullable=True))
    op.alter_column('workflow_attachments', 'data', existing_type=mysql.LONGBLOB(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflow_attachments', 'data', existing_type=mysql.LONGBLOB(), nullable=False)
    op.drop_column('workflow_attachments', 'file')
    # ### end Alembic commands ###
