# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2025 ActiDoo GmbH

"""store bigger specs

Revision ID: 957e40296322
Revises: ce6f4adda3a1
Create Date: 2024-08-20 10:07:20.095768

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql
import actidoo_wfe.database

# revision identifiers, used by Alembic.
revision = '957e40296322'
down_revision = 'ce6f4adda3a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('cache_data',
        sa.Column('namespace', sa.String(length=255), nullable=False),
        sa.Column('key', sa.String(length=255), nullable=False),
        sa.Column('value', actidoo_wfe.database.JSONBlob(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('namespace', 'key', name=op.f('pk_cache_data'))
    )
    op.create_index('ix_cache_created_at', 'cache_data', ['created_at'], unique=False)
    op.create_index('ix_cache_namespace_key', 'cache_data', ['namespace', 'key'], unique=True)

    op.create_table('cache_lock',
        sa.Column('namespace', sa.String(length=255), nullable=False),
        sa.Column('key', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('namespace', 'key', name=op.f('pk_cache_lock'))
    )
    op.create_index('ix_lock_created_at', 'cache_lock', ['created_at'], unique=False)
    op.create_index('ix_lock_namespace_key', 'cache_lock', ['namespace', 'key'], unique=True)

    op.alter_column('workflow_spec_files', 'file_content',
               existing_type=mysql.TEXT(),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
