# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2025 ActiDoo GmbH

"""rename triggered_by

Revision ID: 9f1c3fee8890
Revises: 
Create Date: 2024-07-31 09:04:50.875856

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f1c3fee8890'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflow_instance_tasks', 'triggered_by', new_column_name="triggered_by_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflow_instance_tasks', 'triggered_by_id', new_column_name="triggered_by")
    # ### end Alembic commands ###
