# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2025 ActiDoo GmbH

"""timer events

Revision ID: fb45a9433d17
Revises: 10d894b60910
Create Date: 2025-09-11 08:33:28.661202

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import actidoo_wfe.database

# revision identifiers, used by Alembic.
revision = 'fb45a9433d17'
down_revision = '10d894b60910'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_time_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_instance_id', sa.Uuid(), nullable=False),
    sa.Column('timer_task_id', sa.Uuid(), nullable=False),
    sa.Column('timer_kind', sa.String(length=32), nullable=False),
    sa.Column('expression', sa.Text(), nullable=True),
    sa.Column('interrupting', sa.Boolean(), nullable=False),
    sa.Column('due_at', actidoo_wfe.database.UTCDateTime(), nullable=False),
    sa.Column('remaining_cycles', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('fire_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', actidoo_wfe.database.UTCDateTime(), nullable=False),
    sa.CheckConstraint("status IN ('scheduled','completed','cancelled','error')", name=op.f('ck_workflow_time_events_ck_wte_status_values')),
    sa.ForeignKeyConstraint(['workflow_instance_id'], ['workflow_instances.id'], name=op.f('fk_workflow_time_events_workflow_instance_id_workflow_instances'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_time_events')),
    sa.UniqueConstraint('workflow_instance_id', 'timer_task_id', name='uq_wte_per_task')
    )
    op.create_index(op.f('ix_workflow_time_events_created_at'), 'workflow_time_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_workflow_time_events_due_at'), 'workflow_time_events', ['due_at'], unique=False)
    op.create_index(op.f('ix_workflow_time_events_workflow_instance_id'), 'workflow_time_events', ['workflow_instance_id'], unique=False)
    op.create_index('ix_wte_due_status', 'workflow_time_events', ['due_at', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wte_due_status', table_name='workflow_time_events')
    op.drop_index(op.f('ix_workflow_time_events_workflow_instance_id'), table_name='workflow_time_events')
    op.drop_index(op.f('ix_workflow_time_events_due_at'), table_name='workflow_time_events')
    op.drop_index(op.f('ix_workflow_time_events_created_at'), table_name='workflow_time_events')
    op.drop_table('workflow_time_events')
    # ### end Alembic commands ###
