// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2025 ActiDoo GmbH

import React, { ReactElement } from 'react';
import { evaluateHideIfAndFeel } from '@/services/FeelService';
import {
  buildEvaluationContext,
  buildMaskedParentContext,
  resolveHiddenFields,
} from '@/services/feelContext';
import { InterpreterContext, unaryTest } from 'feelin';
import { FieldProps } from '@rjsf/utils';
import CustomSchemaField from '@/rjsf-customs/custom-fields/CustomSchemaField';

// Conventions:
// No key may be named "root", "this", "parent"
// No key of a Dynamic List may include a "-"

const evaluateHideIf = (expression: string, context: InterpreterContext | undefined): boolean => {
  try {
    return unaryTest(expression, { ...(context ?? {}) });
  } catch {
    return false;
  }
};

const CustomArraySchemaField = (props: FieldProps): ReactElement => {
  const { formData, uiSchema, schema } = props;
  const formContext = (props.registry as any)?.formContext;

  if (uiSchema !== undefined) {
    // "formContext" has the complete global data
    // "formData" has only the data of the current list element
    // In RJSF a list within a list does not know anything about the parent list,
    // there is no directly accessible data in the props about the parent list.
    // But a parent list can be referenced in FEEL expressions with "parent.keyOfParent",
    // therefore we have to use the idSchema (which is actually generated by RJSF to id the html elements)
    // to find the parent list:
    const rootData = formContext?.formData;
    const rootUiSchema = formContext?.uiSchema;
    const maskedRootContext = rootUiSchema
      ? resolveHiddenFields(rootUiSchema, rootData, evaluateHideIf).maskedContext ?? rootData
      : rootData;
    const parent = buildMaskedParentContext(
      rootData,
      rootUiSchema,
      props.idSchema.$id,
      maskedRootContext,
      evaluateHideIf
    );

    const evaluationFields = buildEvaluationContext(maskedRootContext, formData, parent);
    // For compatibility reasons with old forms: buildEvaluationContext adds the data of the
    // current list element to the evaluation context without a "this".
    // In old forms we referenced elements inside a hide-if-condition of the same list WITHOUT
    // the "this." keyword. This did not work in the Camunda Modeler, but was supported here.
    // As soon as all old workflows are completed, we can delete "...formdata" as parameter for evaluationFields.

    const { newUiSchema, newSchema } = evaluateHideIfAndFeel(evaluationFields, uiSchema, schema);
    const newProps = { ...props, uiSchema: newUiSchema, schema: newSchema };

    return <CustomSchemaField {...newProps} />;
  }
  return <CustomSchemaField {...props} />;
};

export default CustomArraySchemaField;
